const authRoute = require("./authentication.routes");
const productRoute = require("./product.routes");
const adminProductRoute = require("./admin.product.routes");
const adminWarehouseRoute = require("./admin.warehouse.routes");
const uploadRoute = require("./upload.routes");
const blogRoute = require("./blog.routes");
const eventRoute = require("./event.routes");
const userRoute = require("./user.route");
const productCategoryRoute = require("./productCategory.routes");
const productTagsRoute = require("./productTag.routes");
const productVariantRoute = require("./productVariant.routes");
const productVariantImageRoute = require("./productVariantImage.routes");
const brandRoute = require("./brand.routes");
const blogAuthorRoute = require("./blogAuthor.routes");
const blogTagRoute = require("./blogTags.routes");
const upholsteryRoute = require("./upholstery.routes");
const blogCategoriesRoute = require("./blogCategory.routes");
const reviewRoute = require("./review.routes");
const customerInquiryRoute = require("./customerInquiry.routes");
const warrantyRoute = require("./warranty.routes");
const orderRoute = require("./order.routes");
const paymentMethodRoute = require("./paymentMethod.routes");
const promotionRoute = require("./promotion.routes");
const addressRoute = require("./address.routes");
const cartRoute = require("./cart.routes");
const registerEventRoute = require("./registerEvent.routes");
const stockItemRoute = require("./stockItem.routes");
const stockMovementRoute = require("./stockMovement.routes");
const warehouseRoute = require("./warehouse.routes");
function route(app) {
  app.use("/api/auth", authRoute);
  app.use("/api/products", productRoute);
  app.use("/api/blogs", blogRoute);
  app.use("/api/events", eventRoute);
  app.use("/api/register-events", registerEventRoute);
  app.use("/api/user", userRoute);
  app.use("/api/product-categories", productCategoryRoute);
  app.use("/api/product-tags", productTagsRoute);
  app.use("/api/product-variant", productVariantRoute);
  app.use("/api/product-variant-image", productVariantImageRoute);
  app.use("/api/brands", brandRoute);
  app.use("/api/blog-author", blogAuthorRoute);
  app.use("/api/blog-tags", blogTagRoute);
  app.use("/api/upholstery", upholsteryRoute);
  app.use("/api/blog-categories", blogCategoriesRoute);
  app.use("/api/reviews", reviewRoute);
  app.use("/api/inquiries", customerInquiryRoute);
  app.use("/api/warranties", warrantyRoute);
  app.use("/api/payment-methods", paymentMethodRoute);
  app.use("/api/promotions", promotionRoute);
  app.use("/api/addresses", addressRoute);
  app.use("/api/cart", cartRoute);
  app.use("/api/orders", orderRoute);
  app.use("/api/stock-items", stockItemRoute);
  app.use("/api/stock-movements", stockMovementRoute);
  app.use("/api/warehouse", warehouseRoute);

  // Admin and Utility Routes
  app.use("/api/admin/products", adminProductRoute);
  app.use("/api/admin/warehouse", adminWarehouseRoute);
  app.use("/api/upload", uploadRoute);
}
module.exports = route;
